branch-defaults:
  master:
    environment: amathon-dev
    group_suffix: null
global:
  application_name: amathon
  branch: null
  default_ec2_keyname: amathon
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: amathon
  repository: null
  sc: git
  workspace_type: Application
