version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/amathon-eb-circleci
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install Dependencies && Build Client
          command: |
            cd client
            npm install
            npm run build
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/amathon-eb-circleci
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile amathon]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
            ls
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb use amathon-dev3 --profile amathon 
            # 현재 eb application 이름과 IAM credentials profile 이름을 적어주세요.
            eb deploy --profile amathon

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master